platform :ios, '9.0'

use_frameworks!

target 'JWAppCheckUpdateKit_Example' do
  pod 'JWAppCheckUpdateKit', :path => '../'

  target 'JWAppCheckUpdateKit_Tests' do
    inherit! :search_paths

    
  end
end
